let secondData = {
  "nodes": [
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 2,
      "seconds_remaining": 24,
      "shot_made_flag": 1,
      "action_type": "Alley Oop Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Boston Celtics",
      "x": 2,
      "y": 16
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 11,
      "seconds_remaining": 15,
      "shot_made_flag": 1,
      "action_type": "Alley Oop Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Cleveland Cavaliers",
      "x": 9,
      "y": 13
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 10,
      "seconds_remaining": 24,
      "shot_made_flag": 1,
      "action_type": "Alley Oop Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": 2,
      "y": 10
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 7,
      "seconds_remaining": 18,
      "shot_made_flag": 1,
      "action_type": "Alley Oop Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Golden State Warriors",
      "x": -2,
      "y": 6
    },
    {
      "id": "Tristan Thompson",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6474,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 0,
      "seconds_remaining": 0,
      "shot_made_flag": 0,
      "action_type": "Alley Oop Layup shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Boston Celtics",
      "x": 13,
      "y": 17
    },
    {
      "id": "Tristan Thompson",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6474,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 4,
      "seconds_remaining": 5,
      "shot_made_flag": 1,
      "action_type": "Alley Oop Layup shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": -2,
      "y": 1
    },
    {
      "id": "Jordan Bell",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 3,
      "seconds_remaining": 15,
      "shot_made_flag": 1,
      "action_type": "Cutting Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Houston Rockets",
      "x": 0,
      "y": 9
    },
    {
      "id": "Jordan Bell",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 53,
      "shot_made_flag": 1,
      "action_type": "Cutting Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Houston Rockets",
      "x": -2,
      "y": 24
    },
    {
      "id": "Jeff Green",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3209,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 10,
      "seconds_remaining": 42,
      "shot_made_flag": 1,
      "action_type": "Cutting Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Boston Celtics",
      "x": 3,
      "y": 26
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 10,
      "seconds_remaining": 17,
      "shot_made_flag": 1,
      "action_type": "Cutting Finger Roll Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": 8,
      "y": 1
    },
    {
      "id": "Jordan Bell",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 35,
      "shot_made_flag": 1,
      "action_type": "Cutting Finger Roll Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Houston Rockets",
      "x": 7,
      "y": 19
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 9,
      "seconds_remaining": 25,
      "shot_made_flag": 1,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Cleveland Cavaliers",
      "x": -2,
      "y": 8
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 8,
      "seconds_remaining": 33,
      "shot_made_flag": 1,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 3,
      "opponent": "Cleveland Cavaliers",
      "x": 24,
      "y": 20
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 6,
      "seconds_remaining": 22,
      "shot_made_flag": 0,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": 3,
      "y": 8
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 51,
      "shot_made_flag": 0,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Cleveland Cavaliers",
      "x": 10,
      "y": 23
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 4,
      "seconds_remaining": 31,
      "shot_made_flag": 1,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": -5,
      "y": 7
    },
    {
      "id": "Jeff Green",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3209,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 2,
      "seconds_remaining": 36,
      "shot_made_flag": 1,
      "action_type": "Cutting Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Boston Celtics",
      "x": -3,
      "y": 17
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 9,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Driving Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Cleveland Cavaliers",
      "x": -11,
      "y": 6
    },
    {
      "id": "Draymond Green",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6589,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 16,
      "shot_made_flag": 1,
      "action_type": "Driving Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Houston Rockets",
      "x": -5,
      "y": 15
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 2,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Driving Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -4,
      "y": 11
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 10,
      "seconds_remaining": 35,
      "shot_made_flag": 0,
      "action_type": "Driving Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Golden State Warriors",
      "x": 3,
      "y": 6
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 45,
      "shot_made_flag": 1,
      "action_type": "Driving Finger Roll Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -1,
      "y": 17
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 5,
      "seconds_remaining": 14,
      "shot_made_flag": 1,
      "action_type": "Driving Floating Bank Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 9,
      "opponent": "Houston Rockets",
      "x": 88,
      "y": 41
    },
    {
      "id": "Jeff Green",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3209,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 2,
      "seconds_remaining": 3,
      "shot_made_flag": 0,
      "action_type": "Driving Floating Bank Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Boston Celtics",
      "x": 54,
      "y": 50
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 39,
      "shot_made_flag": 0,
      "action_type": "Driving Floating Bank Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 6,
      "opponent": "Cleveland Cavaliers",
      "x": 52,
      "y": 37
    },
    {
      "id": "Dwyane Wade",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1987,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 10,
      "seconds_remaining": 5,
      "shot_made_flag": 0,
      "action_type": "Driving Floating Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 13,
      "opponent": "Boston Celtics",
      "x": 20,
      "y": 130
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Driving Floating Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 8,
      "opponent": "Cleveland Cavaliers",
      "x": -86,
      "y": 17
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 15,
      "shot_made_flag": 1,
      "action_type": "Driving Floating Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 9,
      "opponent": "Boston Celtics",
      "x": 70,
      "y": 68
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 1,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Driving Floating Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Boston Celtics",
      "x": -45,
      "y": 57
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 11,
      "seconds_remaining": 44,
      "shot_made_flag": 1,
      "action_type": "Driving Floating Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 10,
      "opponent": "Cleveland Cavaliers",
      "x": -1,
      "y": 100
    },
    {
      "id": "Al Horford",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3213,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 10,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Driving Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 8,
      "opponent": "Cleveland Cavaliers",
      "x": -6,
      "y": 83
    },
    {
      "id": "Trevor Ariza",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2426,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 9,
      "seconds_remaining": 10,
      "shot_made_flag": 0,
      "action_type": "Driving Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Golden State Warriors",
      "x": 41,
      "y": 66
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 2,
      "seconds_remaining": 50,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -8,
      "y": 16
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 34,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Boston Celtics",
      "x": -14,
      "y": 10
    },
    {
      "id": "Luc Mbah a Moute",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3451,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 10,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": -22,
      "y": 7
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 5,
      "seconds_remaining": 1,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": -25,
      "y": 10
    },
    {
      "id": "Patrick McCaw",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3137730,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 1,
      "seconds_remaining": 2,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Houston Rockets",
      "x": 9,
      "y": 16
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 1,
      "seconds_remaining": 32,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -9,
      "y": 11
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 4,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Cleveland Cavaliers",
      "x": 18,
      "y": 15
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 2,
      "seconds_remaining": 46,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Cleveland Cavaliers",
      "x": 2,
      "y": 16
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 10,
      "seconds_remaining": 11,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Boston Celtics",
      "x": 16,
      "y": 5
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 3,
      "seconds_remaining": 28,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Cleveland Cavaliers",
      "x": -16,
      "y": 17
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 18,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -7,
      "y": 18
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 8,
      "seconds_remaining": 19,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": -2,
      "y": 5
    },
    {
      "id": "Luc Mbah a Moute",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3451,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 9,
      "seconds_remaining": 50,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": 16,
      "y": 13
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 8,
      "seconds_remaining": 56,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": 9,
      "y": 5
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 4,
      "seconds_remaining": 34,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": 7,
      "y": 20
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 5,
      "seconds_remaining": 8,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Boston Celtics",
      "x": 8,
      "y": 6
    },
    {
      "id": "Dwyane Wade",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1987,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 5,
      "seconds_remaining": 38,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Boston Celtics",
      "x": 5,
      "y": 1
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 15,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 3,
      "opponent": "Boston Celtics",
      "x": -9,
      "y": 35
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 12,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Cleveland Cavaliers",
      "x": -8,
      "y": 13
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 5,
      "seconds_remaining": 30,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Cleveland Cavaliers",
      "x": 16,
      "y": 17
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 50,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Houston Rockets",
      "x": 7,
      "y": 20
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 6,
      "seconds_remaining": 11,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": -9,
      "y": 24
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 6,
      "seconds_remaining": 54,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Cleveland Cavaliers",
      "x": 7,
      "y": 11
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 32,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": -9,
      "y": 21
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 9,
      "seconds_remaining": 6,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Cleveland Cavaliers",
      "x": -12,
      "y": 22
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 4,
      "seconds_remaining": 14,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Houston Rockets",
      "x": 1,
      "y": 22
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 11,
      "seconds_remaining": 47,
      "shot_made_flag": 1,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Golden State Warriors",
      "x": -10,
      "y": 16
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 58,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 8,
      "opponent": "Boston Celtics",
      "x": 86,
      "y": 8
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 2,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 4,
      "opponent": "Boston Celtics",
      "x": 46,
      "y": 18
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 8,
      "seconds_remaining": 34,
      "shot_made_flag": 0,
      "action_type": "Driving Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 3,
      "opponent": "Cleveland Cavaliers",
      "x": -7,
      "y": 31
    },
    {
      "id": "Luc Mbah a Moute",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3451,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 8,
      "seconds_remaining": 23,
      "shot_made_flag": 1,
      "action_type": "Driving Reverse Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 2,
      "opponent": "Golden State Warriors",
      "x": -20,
      "y": 13
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 11,
      "seconds_remaining": 13,
      "shot_made_flag": 1,
      "action_type": "Driving Reverse Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Houston Rockets",
      "x": -13,
      "y": 14
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 0,
      "shot_made_flag": 0,
      "action_type": "Driving Reverse Layup Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 1,
      "opponent": "Houston Rockets",
      "x": -8,
      "y": 15
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 6,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Dunk Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 0,
      "opponent": "Golden State Warriors",
      "x": -6,
      "y": 7
    },
    {
      "id": "Gordon Hayward",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 4249,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 9,
      "seconds_remaining": 14,
      "shot_made_flag": 1,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 9,
      "opponent": "Cleveland Cavaliers",
      "x": -9,
      "y": 91
    },
    {
      "id": "Trevor Ariza",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2426,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 16,
      "shot_made_flag": 1,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Golden State Warriors",
      "x": -199,
      "y": 148
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 6,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 15,
      "opponent": "Houston Rockets",
      "x": 156,
      "y": 28
    },
    {
      "id": "David West",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2177,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 8,
      "seconds_remaining": 39,
      "shot_made_flag": 1,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 9,
      "opponent": "Houston Rockets",
      "x": 4,
      "y": 99
    },
    {
      "id": "Dwyane Wade",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1987,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 8,
      "seconds_remaining": 21,
      "shot_made_flag": 0,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 14,
      "opponent": "Boston Celtics",
      "x": 148,
      "y": 15
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 5,
      "seconds_remaining": 23,
      "shot_made_flag": 1,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 18,
      "opponent": "Golden State Warriors",
      "x": -165,
      "y": 84
    },
    {
      "id": "Chris Paul",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2779,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 8,
      "seconds_remaining": 0,
      "shot_made_flag": 1,
      "action_type": "Fadeaway Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 12,
      "opponent": "Golden State Warriors",
      "x": -116,
      "y": 34
    },
    {
      "id": "JR Smith",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2444,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 11,
      "seconds_remaining": 23,
      "shot_made_flag": 1,
      "action_type": "Floating Jump shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 13,
      "opponent": "Boston Celtics",
      "x": -24,
      "y": 130
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 45,
      "shot_made_flag": 1,
      "action_type": "Floating Jump shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Houston Rockets",
      "x": 4,
      "y": 74
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 8,
      "seconds_remaining": 0,
      "shot_made_flag": 0,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 5,
      "opponent": "Golden State Warriors",
      "x": 57,
      "y": 16
    },
    {
      "id": "David West",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2177,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 8,
      "seconds_remaining": 24,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 10,
      "opponent": "Houston Rockets",
      "x": 3,
      "y": 106
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 1,
      "seconds_remaining": 55,
      "shot_made_flag": 0,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 8,
      "opponent": "Golden State Warriors",
      "x": -13,
      "y": 79
    },
    {
      "id": "Al Horford",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3213,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 11,
      "seconds_remaining": 25,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 13,
      "opponent": "Cleveland Cavaliers",
      "x": -52,
      "y": 128
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 10,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 3,
      "opponent": "Golden State Warriors",
      "x": 6,
      "y": 34
    },
    {
      "id": "Clint Capela",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3102529,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 9,
      "seconds_remaining": 23,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 5,
      "opponent": "Golden State Warriors",
      "x": -13,
      "y": 53
    },
    {
      "id": "Nick Young",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3243,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 7,
      "seconds_remaining": 7,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 6,
      "opponent": "Houston Rockets",
      "x": -17,
      "y": 58
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 6,
      "seconds_remaining": 56,
      "shot_made_flag": 1,
      "action_type": "Hook Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 5,
      "opponent": "Golden State Warriors",
      "x": 11,
      "y": 52
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 31,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 23,
      "opponent": "Boston Celtics",
      "x": 29,
      "y": 234
    },
    {
      "id": "Terry Rozier",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3074752,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 3,
      "seconds_remaining": 4,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 17,
      "opponent": "Cleveland Cavaliers",
      "x": 133,
      "y": 120
    },
    {
      "id": "Chris Paul",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2779,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 1,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 27,
      "opponent": "Golden State Warriors",
      "x": -13,
      "y": 279
    },
    {
      "id": "Al Horford",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3213,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 10,
      "seconds_remaining": 21,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 16,
      "opponent": "Cleveland Cavaliers",
      "x": 139,
      "y": 82
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 1,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Boston Celtics",
      "x": 135,
      "y": 207
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 52,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 11,
      "opponent": "Golden State Warriors",
      "x": -2,
      "y": 112
    },
    {
      "id": "Chris Paul",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2779,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 3,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": -134,
      "y": 225
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 8,
      "seconds_remaining": 9,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 27,
      "opponent": "Golden State Warriors",
      "x": 42,
      "y": 267
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 29,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Cleveland Cavaliers",
      "x": -231,
      "y": 15
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 1,
      "seconds_remaining": 42,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 16,
      "opponent": "Cleveland Cavaliers",
      "x": -168,
      "y": 21
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 46,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 28,
      "opponent": "Golden State Warriors",
      "x": -107,
      "y": 264
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 4,
      "seconds_remaining": 12,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Cleveland Cavaliers",
      "x": -230,
      "y": 24
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 7,
      "seconds_remaining": 9,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": -218,
      "y": 141
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 5,
      "seconds_remaining": 29,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Golden State Warriors",
      "x": 35,
      "y": 247
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 31,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Golden State Warriors",
      "x": -231,
      "y": 38
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 8,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Boston Celtics",
      "x": -235,
      "y": 43
    },
    {
      "id": "Nick Young",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3243,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 41,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 28,
      "opponent": "Houston Rockets",
      "x": -154,
      "y": 237
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 4,
      "seconds_remaining": 56,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Cleveland Cavaliers",
      "x": 64,
      "y": 237
    },
    {
      "id": "Gordon Hayward",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 4249,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 11,
      "seconds_remaining": 21,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": -214,
      "y": 138
    },
    {
      "id": "Trevor Ariza",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2426,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 10,
      "seconds_remaining": 36,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": -172,
      "y": 183
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 52,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Boston Celtics",
      "x": 239,
      "y": 61
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 4,
      "seconds_remaining": 24,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Golden State Warriors",
      "x": -16,
      "y": 74
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 4,
      "seconds_remaining": 2,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 7,
      "opponent": "Golden State Warriors",
      "x": 20,
      "y": 74
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 27,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": 101,
      "y": 241
    },
    {
      "id": "Jeff Green",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3209,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 34,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Boston Celtics",
      "x": -236,
      "y": 29
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 47,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": 157,
      "y": 200
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 40,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 19,
      "opponent": "Golden State Warriors",
      "x": 173,
      "y": 90
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 9,
      "seconds_remaining": 38,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Boston Celtics",
      "x": 41,
      "y": 244
    },
    {
      "id": "Terry Rozier",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3074752,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 0,
      "seconds_remaining": 25,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Cleveland Cavaliers",
      "x": 31,
      "y": 248
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 6,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": -126,
      "y": 220
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 0,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Cleveland Cavaliers",
      "x": 209,
      "y": 155
    },
    {
      "id": "Terry Rozier",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3074752,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 9,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Cleveland Cavaliers",
      "x": -187,
      "y": 183
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": 58,
      "y": 248
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 47,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 28,
      "opponent": "Boston Celtics",
      "x": -130,
      "y": 258
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 5,
      "seconds_remaining": 35,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 27,
      "opponent": "Boston Celtics",
      "x": 150,
      "y": 225
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 9,
      "seconds_remaining": 35,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Houston Rockets",
      "x": 176,
      "y": 193
    },
    {
      "id": "Draymond Green",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6589,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 11,
      "seconds_remaining": 27,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": 9,
      "y": 254
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 7,
      "seconds_remaining": 28,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Boston Celtics",
      "x": -53,
      "y": 258
    },
    {
      "id": "Chris Paul",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2779,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 11,
      "seconds_remaining": 35,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 10,
      "opponent": "Golden State Warriors",
      "x": 40,
      "y": 101
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 1,
      "seconds_remaining": 38,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": -21,
      "y": 251
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 7,
      "seconds_remaining": 15,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 13,
      "opponent": "Houston Rockets",
      "x": 130,
      "y": 17
    },
    {
      "id": "Al Horford",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3213,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 48,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 19,
      "opponent": "Cleveland Cavaliers",
      "x": 47,
      "y": 190
    },
    {
      "id": "Trevor Ariza",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2426,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 11,
      "seconds_remaining": 4,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": -218,
      "y": 128
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 7,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Houston Rockets",
      "x": -74,
      "y": 256
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 8,
      "seconds_remaining": 15,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 27,
      "opponent": "Houston Rockets",
      "x": -127,
      "y": 239
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 7,
      "seconds_remaining": 3,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": 153,
      "y": 214
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 3,
      "seconds_remaining": 28,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 18,
      "opponent": "Houston Rockets",
      "x": -116,
      "y": 141
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 54,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 22,
      "opponent": "Boston Celtics",
      "x": 225,
      "y": -9
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 3,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": -149,
      "y": 212
    },
    {
      "id": "Al Horford",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3213,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 11,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": 67,
      "y": 245
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 8,
      "seconds_remaining": 57,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": -168,
      "y": 204
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 6,
      "seconds_remaining": 46,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": -105,
      "y": 231
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 5,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": -210,
      "y": 145
    },
    {
      "id": "Eric Gordon",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3431,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 3,
      "seconds_remaining": 59,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": 152,
      "y": 214
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 3,
      "seconds_remaining": 37,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Boston Celtics",
      "x": 80,
      "y": 242
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 0,
      "seconds_remaining": 0,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Boston Celtics",
      "x": -3,
      "y": 262
    },
    {
      "id": "Shaun Livingston",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2393,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 11,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 11,
      "opponent": "Houston Rockets",
      "x": 114,
      "y": 23
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 3,
      "seconds_remaining": 46,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": 170,
      "y": 206
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 3,
      "seconds_remaining": 49,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 20,
      "opponent": "Houston Rockets",
      "x": 110,
      "y": 173
    },
    {
      "id": "Chris Paul",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2779,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 39,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Golden State Warriors",
      "x": 14,
      "y": 243
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 8,
      "seconds_remaining": 39,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 12,
      "opponent": "Houston Rockets",
      "x": 1,
      "y": 127
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 9,
      "seconds_remaining": 51,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": -52,
      "y": 245
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 2,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": -118,
      "y": 224
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 5,
      "seconds_remaining": 44,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 21,
      "opponent": "Boston Celtics",
      "x": -145,
      "y": 162
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 7,
      "seconds_remaining": 52,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 12,
      "opponent": "Houston Rockets",
      "x": 96,
      "y": 79
    },
    {
      "id": "Marcus Smart",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2990992,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 1,
      "seconds_remaining": 13,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 10,
      "opponent": "Cleveland Cavaliers",
      "x": -27,
      "y": 105
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 3,
      "seconds_remaining": 52,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Cleveland Cavaliers",
      "x": -164,
      "y": 202
    },
    {
      "id": "Aron Baynes",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2968439,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 1,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 16,
      "opponent": "Cleveland Cavaliers",
      "x": 69,
      "y": 146
    },
    {
      "id": "JR Smith",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2444,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 3,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 23,
      "opponent": "Boston Celtics",
      "x": 232,
      "y": 27
    },
    {
      "id": "Trevor Ariza",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2426,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 2,
      "seconds_remaining": 9,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": 146,
      "y": 209
    },
    {
      "id": "Derrick Rose",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3456,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 5,
      "seconds_remaining": 59,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 18,
      "opponent": "Boston Celtics",
      "x": 112,
      "y": 150
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 11,
      "seconds_remaining": 2,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 15,
      "opponent": "Boston Celtics",
      "x": -131,
      "y": 83
    },
    {
      "id": "Aron Baynes",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2968439,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 44,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 9,
      "opponent": "Cleveland Cavaliers",
      "x": -28,
      "y": 90
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 6,
      "seconds_remaining": 50,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 22,
      "opponent": "Golden State Warriors",
      "x": 228,
      "y": 10
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 0,
      "seconds_remaining": 11,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Golden State Warriors",
      "x": 141,
      "y": 227
    },
    {
      "id": "Nick Young",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3243,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 10,
      "seconds_remaining": 11,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": 175,
      "y": 187
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 0,
      "seconds_remaining": 57,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 18,
      "opponent": "Boston Celtics",
      "x": 183,
      "y": 32
    },
    {
      "id": "James Harden",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3992,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 9,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 6,
      "opponent": "Golden State Warriors",
      "x": -10,
      "y": 61
    },
    {
      "id": "Nick Young",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3243,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 2,
      "seconds_remaining": 55,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 22,
      "opponent": "Houston Rockets",
      "x": 226,
      "y": 21
    },
    {
      "id": "Shaun Livingston",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2393,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 9,
      "seconds_remaining": 4,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 8,
      "opponent": "Houston Rockets",
      "x": -67,
      "y": 51
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 9,
      "seconds_remaining": 11,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 21,
      "opponent": "Houston Rockets",
      "x": -209,
      "y": 46
    },
    {
      "id": "Luc Mbah a Moute",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3451,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 3,
      "seconds_remaining": 24,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 22,
      "opponent": "Golden State Warriors",
      "x": -225,
      "y": 18
    },
    {
      "id": "PJ Tucker",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3033,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 2,
      "seconds_remaining": 43,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 22,
      "opponent": "Golden State Warriors",
      "x": 227,
      "y": 7
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 5,
      "seconds_remaining": 55,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Boston Celtics",
      "x": 119,
      "y": 228
    },
    {
      "id": "Kevin Love",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3449,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 7,
      "seconds_remaining": 51,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 19,
      "opponent": "Boston Celtics",
      "x": -133,
      "y": 146
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 5,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 21,
      "opponent": "Houston Rockets",
      "x": -142,
      "y": 163
    },
    {
      "id": "Jae Crowder",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6581,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 10,
      "seconds_remaining": 21,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 22,
      "opponent": "Boston Celtics",
      "x": 217,
      "y": 56
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 5,
      "seconds_remaining": 17,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 28,
      "opponent": "Golden State Warriors",
      "x": -71,
      "y": 281
    },
    {
      "id": "LeBron James",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 1966,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 3,
      "seconds_remaining": 21,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Boston Celtics",
      "x": -98,
      "y": 241
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 27,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 29,
      "opponent": "Cleveland Cavaliers",
      "x": -196,
      "y": 227
    },
    {
      "id": "JR Smith",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2444,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 1,
      "minutes_remaining": 4,
      "seconds_remaining": 47,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Boston Celtics",
      "x": -70,
      "y": 243
    },
    {
      "id": "JR Smith",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2444,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 2,
      "minutes_remaining": 1,
      "seconds_remaining": 38,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 17,
      "opponent": "Boston Celtics",
      "x": 6,
      "y": 174
    },
    {
      "id": "Jaylen Brown",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3917376,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 4,
      "seconds_remaining": 8,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": -223,
      "y": 129
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 5,
      "seconds_remaining": 33,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 29,
      "opponent": "Cleveland Cavaliers",
      "x": 142,
      "y": 258
    },
    {
      "id": "Jeff Green",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3209,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 4,
      "minutes_remaining": 9,
      "seconds_remaining": 25,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 11,
      "opponent": "Boston Celtics",
      "x": 57,
      "y": 96
    },
    {
      "id": "Jayson Tatum",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": "",
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 4,
      "seconds_remaining": 15,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "2PT Field Goal",
      "shot_distance": 12,
      "opponent": "Cleveland Cavaliers",
      "x": -96,
      "y": 80
    },
    {
      "id": "Stephen Curry",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3975,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 10,
      "seconds_remaining": 6,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 26,
      "opponent": "Houston Rockets",
      "x": 168,
      "y": 208
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 8,
      "seconds_remaining": 39,
      "shot_made_flag": 1,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Golden State Warriors",
      "x": 160,
      "y": 204
    },
    {
      "id": "Kevin Durant",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3202,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 3,
      "minutes_remaining": 4,
      "seconds_remaining": 36,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Houston Rockets",
      "x": 170,
      "y": 182
    },
    {
      "id": "JR Smith",
      "group": "Cleveland Cavaliers",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 2444,
      "team_id": 1610612739,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 5,
      "seconds_remaining": 17,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Boston Celtics",
      "x": 178,
      "y": 185
    },
    {
      "id": "Ryan Anderson",
      "group": "Houston Rockets",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 3412,
      "team_id": 1610612745,
      "espn_game_id": 400974438,
      "period": 2,
      "minutes_remaining": 4,
      "seconds_remaining": 47,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 24,
      "opponent": "Golden State Warriors",
      "x": 212,
      "y": 122
    },
    {
      "id": "Kyrie Irving",
      "group": "Boston Celtics",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6442,
      "team_id": 1610612738,
      "espn_game_id": 400974437,
      "period": 3,
      "minutes_remaining": 7,
      "seconds_remaining": 12,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Cleveland Cavaliers",
      "x": 3,
      "y": 255
    },
    {
      "id": "Klay Thompson",
      "group": "Golden State Warriors",
      "game_date": "10/17/17",
      "season": 2017,
      "espn_player_id": 6475,
      "team_id": 1610612744,
      "espn_game_id": 400974438,
      "period": 4,
      "minutes_remaining": 4,
      "seconds_remaining": 52,
      "shot_made_flag": 0,
      "action_type": "Jump Shot",
      "shot_type": "3PT Field Goal",
      "shot_distance": 25,
      "opponent": "Houston Rockets",
      "x": 158,
      "y": 205
    }
  ], "links": []
}